functionsDirectory = "/Users/nicoguyon/BrandFou/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/nicoguyon/BrandFou/public"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npm run build"
functions = "/Users/nicoguyon/BrandFou/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
port = 3000.0
publish = "public"

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]